### ISSUE TITLE
Typo "admininistration" in documentation

### ISSUE THREAD

**Issue by tc-Jana** [shopware/swag-docs-custom-module#1]
While following the documentation for this repository I noticed that there is a typo which breaks the plugin. 

Please change "admininistration" to "administration" in the file path under the headline "Injecting into the administration" in the documentation on how to "Add new module to administration."

https://docs.shopware.com/en/shopware-platform-dev-en/how-to/custom-module?category=shopware-platform-dev-en/how-to

**Comment by mitelg** [comment]
thanks for the hint @tc-Jana :+1: 
I created an internal PR for that, as it was wrong in almost every admin doc fiel :smile: :see_no_evil: 
Will be fixed soon
